### ISSUE TITLE
[Feature] Add support for the Zephyr Cloud API

### ISSUE THREAD

**Issue by elaichenkov** [elaichenkov/playwright-zephyr#1]
Currently, the reporter works only for the Server API

**Comment by lewham** [comment]
Any plans to add this soon? This would be very helpful.

**Comment by klepik1990** [comment]
Hey guys, are there any news about this killer feature?

**Comment by elaichenkov** [comment]
Hey @lewham and @klepik1990 
Sorry for the late reply. I'll try to take a look at it this weekend and I'll give you an update on it.

**Comment by klepik1990** [comment]
@elaichenkov Hi there! Do you have any updates?

**Comment by sukhjindersukh** [comment]
Hi @elaichenkov, This is the much needed feature, could you please help the community by adding it.

**Comment by bonjhhh** [comment]
Hello @elaichenkov , May I request if there are any updates on this? I would really appreciate to have this feature. Thanks.

**Comment by dylanz** [comment]
@Marcin3 this is great workaround, and thanks for that link!

Just export your tests in junit xml format:
`PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml npx playwright test tests/mytest.spec.ts --reporter=junit`

... then post them to Zephyr cloud:
`curl -H "Authorization: Bearer your_token_here" -F "file=@results.xml;type=application/xml" https://api.zephyrscale.smartbear.com/v2/automations/executions/junit?projectKey="your_project_key"&autoCreateTestCases=true`

**Comment by elaichenkov** [comment]
Finally, I've added support for the Cloud API. So, please, update the library to the `1.0.3` version and add cloud reporter into your `playwright.config.ts` file:

```typescript
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  reporter: [
    ['playwright-zephyr/lib/src/cloud', {
      projectKey: 'JARV', // <-- Replace with your project key
      authorizationToken: process.env.ZEPHYR_AUTH_TOKEN, // <-- Replace with your authorization token
    }],
  ],
}
```
