### ISSUE TITLE
Unsuccessful Connection

### ISSUE THREAD

**Issue by davilafuentes** [elaichenkov/playwright-zephyr#12]
When trying to use the library after corresponding configuration with authentication token, I get the following error: "Data: 'Basic authentication with passwords is deprecated." This is returning me 401 code. 

Also, after checking API request, I see the following in headers: 

```
headers: {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/json',
    Authorization: 'Basic 3cLJWXI9oURy4JjkrzgfDEXX',
    'User-Agent': 'axios/0.24.0',
    'Content-Length': 934
  },
```

**Comment by mechandan** [comment]
Agree , always getting 401 error

**Comment by elaichenkov** [comment]
Finally, I've added support for the Cloud API. So, please, update the library to the 1.0.3 version and add cloud reporter into your `playwright.config.ts` file:

```typescript
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  reporter: [
    ['playwright-zephyr/lib/src/cloud', {
      projectKey: 'JARV', // <-- Replace with your project key
      authorizationToken: process.env.ZEPHYR_AUTH_TOKEN, // <-- Replace with your authorization token
    }],
  ],
}
```
