### ISSUE TITLE
Proxy issue - add an option to inject a custom proxy for the service

### ISSUE THREAD

**Issue by hejhj** [elaichenkov/playwright-zephyr#4]
This is an excellent plugin. Nice work!
I'm using it today, turned out running behind the company proxy is problematic(self-signed certificate, HTTP proxy, calling HTTPS api).
I have to manually add a proxy config in zephyr.service.js
```
const httpsAgent = new https.Agent ({
        requestcert: true,
        rejectUnauthorized: false,
        baseURL: this.url
        proxy: {
          host: 'localhost',
          port: 3128,
        }});
this.axios = axios_1.default.create( {
        baseURL: this.url,
        proxy: false, 
        httpsAgent: httpsAgent,
        headers: {
        'Content-Type': 'application/json',
        Authorization: `Basic ${this.authorizationToken}`,
        }));
```

Maybe add an option to inject a custom proxy for the service?

**Comment by hejhj** [comment]
Thanks for the quick fix. But the proxy config wasn't passed to the constructor. 
I've done a sample change here and it works:
https://github.com/elaichenkov/playwright-zephyr/compare/main...hejhj:main

**Comment by elaichenkov** [comment]
Sorry, missed this part. I've updated and released. Can you please check it again?

**Comment by hejhj** [comment]
It works. Thank you.

**Comment by maikwebermsg** [comment]
Hello, i was running into same problem. Is there any example how to use proxy settings for latest version now?

**Comment by ssg0ku** [comment]
@elaichenkov does this still work in the latest version? We are using Zephyr cloud and are behind a corporate proxy.
