### ISSUE TITLE
Not able to use the feature

### ISSUE THREAD

**Issue by sukhjindersukh** [elaichenkov/playwright-zephyr#9]
I want to upload my run results to Zephyr but  I am getting the below error 
Basic authentication with passwords is deprecated.

Here is the reporter configs
['playwright-zephyr', { 
      host: 'https://------.atlassian.net/jira',
      user: 'xxx@sasas.com',
      password: 'ABCDE@123',
      authorizationToken:'563556353563hdsdgh',
      projectKey: 'KEY'
    }]

Please help

**Comment by Marcin3** [comment]
Hello. Could you change this PR? https://github.com/elaichenkov/playwright-zephyr/pull/11 For me now it return 500 so I have no idea if it works

**Comment by elaichenkov** [comment]
Finally, I've added support for the Cloud API. So, please, update the library to the 1.0.3 version and add cloud reporter into your `playwright.config.ts` file:

```typescript
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  reporter: [
    ['playwright-zephyr/lib/src/cloud', {
      projectKey: 'JARV', // <-- Replace with your project key
      authorizationToken: process.env.ZEPHYR_AUTH_TOKEN, // <-- Replace with your authorization token
    }],
  ],
}
```
